name: CI

on: [push]

jobs:
  prepare-job:
    runs-on: ubuntu-latest
    container:
      image: node:10.24.1

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  build-job:
    needs: prepare-job
    runs-on: ubuntu-latest
    container:
      image: node:10.24.1

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: npm run build

  zip-job:
    needs: build-job
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        apk add zip

    - name: Zip files
      run: |
        cd icon-font
        zip -r icon-font.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: icon-font.zip
        path: icon-font/icon-font.zip
