name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:10.24.1-alpine

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Zip files
      run: |
        apk add zip
        cd icon-font
        zip -r icon-font.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: icon-font.zip
        path: icon-font/icon-font.zip
